dataset:
  name: clothing1M_cleanval
  num_classes: 14
  pre_size: 256
  image_size: 224

  interpolation: bilinear
  normalization_type: clothing1M

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [train, val, test]

  train:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/clothing1M/train_clothing1M_noisy.txt
    batch_size: 128
    shuffle: True
  val:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/clothing1M/val_clothing1M_clean.txt
    batch_size: 200
    shuffle: False
  test:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/clothing1M/test_clothing1M_clean.txt
    batch_size: 200
    shuffle: False
